Daniel/delete node fix
geops/openlayers-editor pull request #191
Opened 2020-10-21 10:11 UTC by danji90

2020-10-21 11:24 UTC, friedjoff requested changes

2020-10-21 11:24 UTC, friedjoff commented on src/interaction/select.js
> +          if (this.filter_(feature, layer) && layer) {
Tiny perfomance suggestion:
```suggestion
          if (layer && this.filter_(feature, layer)) {
```

2020-10-21 11:24 UTC, friedjoff commented on src/interaction/select.js
> +          if (this.filter_(feature, layer) && layer) {
```suggestion
          if (layer && this.filter_(feature, layer)) {
```

2020-10-21 11:48 UTC, danji90 commented
@friedjoff Thanks for the suggestions, they've been applied. I also published a beta and successfully tested in mapset

2020-10-22 04:42 UTC, friedjoff approved these changes

2020-10-22 07:33 UTC, merged